### PR TITLE
Issue 54 refactor

### PR DESCRIPTION
**Pull request by bcipolli**
See #54  :(

### CODE REVIEW

**Comment by atsuch** [comment]
Thank you. This is nice. But thinking about restructuring the code... I wonder if it's worth rewriting things using doit (http://pydoit.org/). Are you familiar with this, @bcipolli ? I've used it to make simple pipelines for my imaging analyses, but basically it detects dependencies of particular task, and won't repeat the analysis if it was done and output file exists, unless the code for the previous task has changed. What do you think?

**Comment by bcipolli** [comment]
Looks interesting to me. I'd suggest opening a ticket for that and try that out after merging this. What do you think?

**Comment by atsuch** [comment]
Great. Then I'll merge this. OK?

**Comment by bcipolli** [comment]
I am very much 👍 for merging of my own code :)

**Pull request merged**
